// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaxgpxcfjdbzlkhxdnij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhheGdweGNmamRiemxraHhkbmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODI0NjIsImV4cCI6MjA2ODI1ODQ2Mn0.mg_X6MdD9kP0dWCds9BvIHS16JCtTziqDbhYDjr0nHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});